#!/usr/bin/env node
// Generates frontend/src/generated/docs.ts from top-level public docs/
// Run before building: node scripts/generate-docs.mjs

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname, basename, extname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../");
const docsDir = resolve(repoRoot, "docs");
const outFile = resolve(__dirname, "../src/generated/docs.ts");

const EXPLICIT_EXCLUDES = new Set(["tls-caddy-plan.md"]);

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-");
}

function extractTitle(content, filename) {
  const match = content.match(/^#\s+(.+)/m);
  if (match) return match[1].trim();
  return basename(filename, extname(filename)).replace(/-/g, " ");
}

function extractHeadings(content) {
  const headings = [];
  const lines = content.split("\n");
  let inFence = false;
  for (const line of lines) {
    if (line.startsWith("```")) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const m = line.match(/^(#{1,6})\s+(.+)/);
    if (m) {
      const level = m[1].length;
      const text = m[2].trim();
      const anchor = slugify(text);
      headings.push({ level, text, anchor });
    }
  }
  return headings;
}

function stripMarkdown(content) {
  return content
    // Remove fenced code blocks
    .replace(/```[\s\S]*?```/g, " ")
    // Remove inline code
    .replace(/`[^`]*`/g, " ")
    // Remove headings markers
    .replace(/^#{1,6}\s+/gm, "")
    // Remove bold/italic
    .replace(/[*_]{1,3}([^*_]+)[*_]{1,3}/g, "$1")
    // Remove links, keep text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    // Remove images
    .replace(/!\[[^\]]*\]\([^)]+\)/g, "")
    // Remove HTML tags
    .replace(/<[^>]+>/g, " ")
    // Remove table pipes
    .replace(/\|/g, " ")
    // Collapse whitespace
    .replace(/\s+/g, " ")
    .trim();
}

function escapeTs(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const entries = readdirSync(docsDir)
  .filter((f) => f.endsWith(".md") && !EXPLICIT_EXCLUDES.has(f))
  .sort()
  .map((filename) => {
    const sourcePath = `docs/${filename}`;
    const id = basename(filename, ".md");
    const content = readFileSync(resolve(docsDir, filename), "utf-8");
    const title = extractTitle(content, filename);
    const headings = extractHeadings(content);
    const searchBody = stripMarkdown(content);
    return { id, title, sourcePath, content, headings, searchBody };
  });

const lines = [
  "// AUTO-GENERATED by scripts/generate-docs.mjs — do not edit by hand",
  "// Regenerate: node scripts/generate-docs.mjs",
  "",
  "export interface DocHeading {",
  "  level: number;",
  "  text: string;",
  "  anchor: string;",
  "}",
  "",
  "export interface DocRecord {",
  "  id: string;",
  "  title: string;",
  "  sourcePath: string;",
  "  content: string;",
  "  headings: DocHeading[];",
  "  searchBody: string;",
  "}",
  "",
  "export const generatedDocs: DocRecord[] = [",
  ...entries.map(({ id, title, sourcePath, content, headings, searchBody }) => [
    "  {",
    `    id: ${JSON.stringify(id)},`,
    `    title: ${JSON.stringify(title)},`,
    `    sourcePath: ${JSON.stringify(sourcePath)},`,
    `    content: \`${escapeTs(content)}\`,`,
    `    headings: ${JSON.stringify(headings, null, 2).replace(/\n/g, "\n    ")},`,
    `    searchBody: ${JSON.stringify(searchBody)},`,
    "  },",
  ].join("\n")),
  "];",
  "",
];

writeFileSync(outFile, lines.join("\n"), "utf-8");
console.log(`Generated ${entries.length} doc(s) → ${outFile}`);
