agent_api_key: ${LLAMA_PACK_AGENT_API_KEY}
test_chat_api_key: ${LLAMA_PACK_TEST_CHAT_API_KEY}
controller_registration_key: ${LLAMA_PACK_CONTROLLER_REGISTRATION_KEY}
controller_registration_key_outbound: ${LLAMA_PACK_CONTROLLER_REGISTRATION_KEY_OUTBOUND}
